version: 2
jobs:
   java_8_test_current:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Java 8 - Test current version
            command: ./mvnw -Pdistribute,snapshot,docs clean test

   deploy:
     docker:
       - image: circleci/openjdk:8u141
     steps:
        - checkout
        - run:
            name: Deploy to Artifactory
            command: ./deploy.bash
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - java_8_test_current
      - deploy:
          requires:
            - java_8_test_current

general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

dependencies:
  cache_directories:
    - "~/.m2"
